- name: Configuring Frontend Server
  hosts: frontend
  become: yes
  tasks:
  - name: Disabling nginx
    ansible.builtin.command: dnf module disable nginx -y
  
  - name: Enabling nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: Installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Start & Enable Nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: remove html content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent 
  
  - name: Create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download the frontend content
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: Extract the code
    ansible.builtin.unarchive:
     src: /tmp/frontend.zip
     dest: /usr/share/nginx/html
     remote_src: yes

  - name: Copy nginx service
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted