- name: Cofiguring Rabbit MQ Server
  hosts: rabbitmq
  become: yes
  tasks: 
  - name: Copying rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: Installing rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state:  installed

  - name: Starting and enabling service
    ansible.builtin.service:
      name: rabbitmq-server
      enabled: yes

  - name: Setting username and password
    community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present